version: '3.8'

services:
  frontend:
    build: ./Frontend
    ports:
      - "8647:80"
    depends_on:
      - backend

  hr_page:
    build: ./HR_Page
    ports:
      - "8648:80"
    depends_on:
      - backend

  backend:
    build: ./Backend
    ports:
      - "3175:3175"
    environment:
      - PORT=3175
      - HOST=0.0.0.0
      - DB_USER=postgres
      - DB_PASSWORD=admin321
      - DB_NAME=new_employee_db
      - DB_HOST=postgres
      - DB_PORT=5432
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    restart: always
    ports:
      - "5537:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin321
      POSTGRES_DB: new_employee_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

